name: CI-CD
on:
  push:
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: "Obtendo um código"
      uses: actions/checkout@v4
    - name: "Autenticação no Docker Hub"
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME}}
        password: ${{ secrets.DOCKERHUB_TOKEN}}
    - name: Build da Imagem Docker
      uses: docker/build-push-action@v6
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          thiagomsarrais/aula-primeira-pipeline:v${{ github.run_number }}
          thiagomsarrais/aula-primeira-pipeline:latest
  CD-homologacao:
    needs: [CI]
    uses: thiagomsarrais/primeira-pipeline-cicd/.github/workflows/deploy.yml@main
    with:
      manifest: k8s/deployment.yaml
      images: thiagomsarrais/aula-primeira-pipeline:v${{ github.run_number }}
      environment: homologacao
    secrets: inherit
  Teste-Ambiente:
    needs: [CD-homologacao]
    runs-on: ubuntu-latest
    environment: homologacao
    steps:
      - name: "Fake Teste"
        run: echo "Fake teste ambiente de ${{ vars.APP_NAMESPACE }}"
  CD-producao:
    needs: [Teste-Ambiente]
    uses: thiagomsarrais/primeira-pipeline-cicd/.github/workflows/deploy.yml@main
    with:
      manifest: k8s/deployment.yaml
      images: thiagomsarrais/aula-primeira-pipeline:v${{ github.run_number }}
      environment: producao
    secrets: inherit
