name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: "Obtendo um código"
      uses: actions/checkout@v4
    - name: "Autenticação no Docker Hub"
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME}}
        password: ${{ secrets.DOCKERHUB_TOKEN}}
    - name: Build da Imagem Docker
      uses: docker/build-push-action@v6
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          thiagomsarrais/aula-primeira-pipeline:v${{ github.run_number }}
          thiagomsarrais/aula-primeira-pipeline:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: "Obtendo um código"
      uses: actions/checkout@v4
    - name: Configuração de contexto do Kubernetes
      uses: azure/k8s-set-context@v4.0.1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_CONFIG}}
    - name:  Execução por manifesto
      uses: Azure/k8s-deploy@v5
      with:
         manifests: |
            k8s/deployment.yaml
         images: |
          thiagomsarrais/aula-primeira-pipeline:v${{ github.run_number }}
    
