name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: "Obtendo um código"
      uses: actions/checkout@v4
    - name: "Autenticação no Docker Hub"
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME}}
        password: ${{ secrets.DOCKERHUB_TOKEN}}
    - name: Build da Imagem Docker
      uses: docker/build-push-action@v6
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          thiagomsarrais/aula-primeira-pipeline:v${{ github.run_number }}
          thiagomsarrais/aula-primeira-pipeline:latest
  CD:
    needs: [CI]
    uses: thiagomsarrais/primeira-pipeline-cicd/.github/workflows/deploy.yml@main
    secrets: inherit
